### ISSUE TITLE
cannot unmarshal number into Go struct field USW.stp_priority of type string

### ISSUE THREAD

**Issue by jussisallinen** [golift/unifi#30]
Running UniFi Controller 5.11.39 & USW 4.0.54.10625

`Sep 13 10:40:10 localhost unifi-poller[4130]: 2019/09/13 10:40:10.461631 devices.go:76: [ERROR] json.Unmarshal(usw): json: cannot unmarshal number into Go struct field USW.stp_priority of type string
Sep 13 10:40:10 localhost unifi-poller[4130]: 2019/09/13 10:40:10.461673 devices.go:77: [ERROR] Enable Debug Logging to output the failed payload.
Sep 13 10:40:10 localhost unifi-poller[4130]: 2019/09/13 10:40:10.461732 devices.go:79: [DEBUG] Failed Payload: {"_id":"598c2e16f62eb3ad7244b62b","inform_url":"http://unifi.foo.bar:8080/inform","port_table":[{"port_idx":1,"media":"GE","port_poe":true,"poe_caps":7,"speed_caps":1048623,"op_mode":"switch","portconf_id":"597f622ef62e74498be19d82","poe_mode":"auto","autoneg":true,"dot1x_mode":"unknown","dot1x_status":"disabled","enable":true,"flowctrl_rx":false,"flowctrl_tx":false,"full_duplex":true,"is_uplink":false,"jumbo":false,"lldp_table":[],"poe_class":"Class 4","poe_current":"74.70","poe_enable":true,"poe_good":true,"poe_power":"3.99","poe_voltage":"53.40","rx_broadcast":40941,"rx_bytes":23231572387,"rx_dropped":0,"rx_errors":0,"rx_multicast":1703530,"rx_packets":165271401,"satisfaction":100,"speed":1000,"stp_pathcost":20000,"stp_state":"forwarding","tx_broadcast":587533,"tx_bytes":906402777198,"tx_dropped":0,"tx_errors":0,"tx_multicast":2194058,"tx_packets":628804357,"up":true,"tx_bytes-r":520986,"rx_bytes-r":5198,"bytes-r":526184,"isolation":false,"name":"ge-0.wap1.site1.foo.bar","stormctrl_bcast_enabled":false,"stormctrl_mcast_enabled":false,"stormctrl_ucast_enabled":false,"masked":false,"aggregated_by":false},{"port_idx":2,"media":"GE","port_poe":true,"poe_caps":7,"speed_caps":1048623,"op_mode":"switch","portconf_id":"597f622ef62e74498be19d82","poe_mode":"auto","autoneg":true,"dot1x_mode":"unknown","dot1x_status":"disabled","enable":true,"flowctrl_rx":false,"flowctrl_tx":false,"full_duplex":true,"is_uplink":false,"jumbo":false,"lldp_table":[],"poe_class":"Class 4","poe_current":"60.18","poe_enable":true,"poe_good":true,"poe_power":"3.21","poe_voltage":"53.27","rx_broadcast":196256,"rx_bytes":2164756965,"rx_dropped":0,"rx_errors":0,"rx_multicast":87644,"rx_packets":8247525,"satisfaction":100,"speed":1000,"stp_pathcost":20000,"stp_state":"forwarding","tx_broadcast":431939,"tx_bytes":13824027908,"tx_dropped":0,"tx_errors":0,"tx_multicast":3809944,"tx_packets":15549138,"up":true,"tx_bytes-r":393,"rx_bytes-r":149,"bytes-r":542,"isolation":false,"name":"g
Sep 13 10:40:10 localhost unifi-poller[4130]: e-0.wap2.site1.foo.bar","stormctrl_bcast_enabled":false,"stormctrl_mcast_enabled":false,"stormctrl_ucast_enabled":false,"masked":false,"aggregated_by":false},{"port_idx":3,"media":"GE","port_poe":true,"poe_caps":7,"speed_caps":1048623,"op_mode":"switch","portconf_id":"597f622ef62e74498be19d84","poe_mode":"auto","autoneg":true,"dot1x_mode":"unknown","dot1x_status":"disabled","enable":true,"flowctrl_rx":false,"flowctrl_tx":false,"full_duplex":true,"is_uplink":false,"jumbo":false,"lldp_table":[],"poe_class":"Class 4","poe_current":"59.44","poe_enable":true,"poe_good":true,"poe_power":"3.16","poe_voltage":"53.14","rx_broadcast":83,"rx_bytes":377675043937,"rx_dropped":0,"rx_errors":0,"rx_multicast":0,"rx_packets":277354243,"satisfaction":100,"speed":100,"stp_pathcost":200000,"stp_state":"forwarding","tx_broadcast":628326,"tx_bytes":12096103183,"tx_dropped":0,"tx_errors":0,"tx_multicast":3897647,"tx_packets":161755046,"up":true,"tx_bytes-r":3982,"rx_bytes-r":110501,"bytes-r":114484,"name":"unifi-video-cottage","masked":false,"aggregated_by":false},{"port_idx":4,"media":"GE","port_poe":true,"poe_caps":7,"speed_caps":1048623,"op_mode":"switch","portconf_id":"597f622ef62e74498be19d83","poe_mode":"auto","autoneg":true,"dot1x_mode":"unknown","dot1x_status":"disabled","enable":false,"flowctrl_rx":false,"flowctrl_tx":false,"full_duplex":false,"is_uplink":false,"jumbo":false,"lldp_table":[],"poe_class":"Unknown","poe_current":"0.00","poe_enable":false,"poe_good":false,"poe_power":"0.00","poe_voltage":"0.00","rx_broadcast":0,"rx_bytes":0,"rx_dropped":0,"rx_errors":0,"rx_multicast":0,"rx_packets":0,"satisfaction":100,"speed":0,"stp_pathcost":0,"stp_state":"disabled","tx_broadcast":0,"tx_bytes":0,"tx_dropped":0,"tx_errors":0,"tx_multicast":0,"tx_packets":0,"up":false,"tx_bytes-r":0,"rx_bytes-r":0,"bytes-r":0,"isolation":false,"name":"Port 4","stormctrl_bcast_enabled":false,"stormctrl_mcast_enabled":false,"stormctrl_ucast_enabled":false,"masked":false,"aggregated_by":false},{"port_idx":5,"media":"GE","port_poe":true,"poe_caps"
Sep 13 10:40:10 localhost unifi-poller[4130]: :7,"speed_caps":1048623,"op_mode":"switch","portconf_id":"597f622ef62e74498be19d82","poe_mode":"auto","autoneg":true,"dot1x_mode":"unknown","dot1x_status":"disabled","enable":true,"flowctrl_rx":false,"flowctrl_tx":false,"full_duplex":true,"is_uplink":false,"jumbo":false,"lldp_table":[],"poe_class":"Unknown","poe_current":"0.00","poe_enable":false,"poe_good":false,"poe_power":"0.00","poe_voltage":"0.00","rx_broadcast":40,"rx_bytes":229233398,"rx_dropped":0,"rx_errors":0,"rx_multicast":388873,"rx_packets":810480,"satisfaction":100,"speed":100,"stp_pathcost":200000,"stp_state":"forwarding","tx_broadcast":628370,"tx_bytes":747328563,"tx_dropped":0,"tx_errors":0,"tx_multicast":3508775,"tx_packets":4480680,"up":true,"tx_bytes-r":319,"rx_bytes-r":84,"bytes-r":403,"name":"Port 5","masked":false,"aggregated_by":false},{"port_idx":6,"media":"GE","port_poe":true,"poe_caps":7,"speed_caps":1048623,"op_mode":"switch","portconf_id":"597f622ef62e74498be19d82","poe_mode":"off","autoneg":true,"dot1x_mode":"unknown","dot1x_status":"disabled","enable":true,"flowctrl_rx":false,"flowctrl_tx":false,"full_duplex":true,"is_uplink":false,"jumbo":false,"lldp_table":[],"poe_class":"Unknown","poe_current":"0.00","poe_enable":false,"poe_good":false,"poe_power":"0.00","poe_voltage":"0.00","rx_broadcast":112384,"rx_bytes":394476944,"rx_dropped":0,"rx_errors":0,"rx_multicast":24114,"rx_packets":3413514,"satisfaction":100,"speed":100,"stp_pathcost":200000,"stp_state":"forwarding","tx_broadcast":516019,"tx_bytes":1059874327,"tx_dropped":0,"tx_errors":0,"tx_multicast":3873531,"tx_packets":7668436,"up":true,"tx_bytes-r":441,"rx_bytes-r":151,"bytes-r":593,"name":"en-0.ups1.site1.foo.bar","masked":false,"aggregated_by":false},{"port_idx":7,"media":"GE","port_poe":true,"poe_caps":7,"speed_caps":1048623,"op_mode":"switch","portconf_id":"597f622ef62e74498be19d82","poe_mode":"off","autoneg":true,"dot1x_mode":"unknown","dot1x_status":"disabled","enable":true,"flowctrl_rx":false,"flowctrl_tx":false,"full_duplex":true,"is_uplink":false,"jumbo":false,"lld
Sep 13 10:40:10 localhost unifi-poller[4130]: p_table":[],"poe_class":"Unknown","poe_current":"0.00","poe_enable":false,"poe_good":false,"poe_power":"0.00","poe_voltage":"0.00","rx_broadcast":160,"rx_bytes":2011157563,"rx_dropped":0,"rx_errors":0,"rx_multicast":118035,"rx_packets":12252923,"satisfaction":100,"speed":100,"stp_pathcost":200000,"stp_state":"forwarding","tx_broadcast":628246,"tx_bytes":9768120171,"tx_dropped":0,"tx_errors":0,"tx_multicast":3779641,"tx_packets":22863939,"up":true,"tx_bytes-r":833,"rx_bytes-r":851,"bytes-r":1684,"name":"en-0.raspberrypi.site1.foo.bar","masked":false,"aggregated_by":false},{"port_idx":8,"media":"GE","port_poe":true,"poe_caps":7,"speed_caps":1048623,"op_mode":"switch","portconf_id":"597f622ef62e74498be19d83","poe_mode":"off","autoneg":true,"dot1x_mode":"unknown","dot1x_status":"disabled","enable":false,"flowctrl_rx":false,"flowctrl_tx":false,"full_duplex":false,"is_uplink":false,"jumbo":false,"lldp_table":[],"poe_class":"Unknown","poe_current":"0.00","poe_enable":false,"poe_good":false,"poe_power":"0.00","poe_voltage":"0.00","rx_broadcast":0,"rx_bytes":0,"rx_dropped":0,"rx_errors":0,"rx_multicast":0,"rx_packets":0,"satisfaction":100,"speed":0,"stp_pathcost":0,"stp_state":"disabled","tx_broadcast":0,"tx_bytes":0,"tx_dropped":0,"tx_errors":0,"tx_multicast":0,"tx_packets":0,"up":false,"tx_bytes-r":0,"rx_bytes-r":0,"bytes-r":0,"name":"Port 8","masked":false,"aggregated_by":false},{"port_idx":9,"media":"SFP","port_poe":false,"poe_caps":0,"speed_caps":1048608,"op_mode":"switch","portconf_id":"597f622ef62e74498be19d82","autoneg":true,"dot1x_mode":"unknown","dot1x_status":"disabled","enable":true,"flowctrl_rx":false,"flowctrl_tx":false,"full_duplex":true,"is_uplink":true,"jumbo":false,"lldp_table":[{"lldp_chassis_id":"78:8A:20:FD:62:EE","lldp_port_id":"0/26","lldp_system_name":"cr-sw2"}],"rx_broadcast":212212,"rx_bytes":931434428704,"rx_dropped":0,"rx_errors":0,"rx_multicast":1575479,"rx_packets":804298097,"satisfaction":100,"sfp_compliance":"Unknown","sfp_current":"0.000","sfp_found":true,"sfp_part":"SFP-GE-BX","sfp_re
Sep 13 10:40:10 localhost unifi-poller[4130]: v":"A0","sfp_rxfault":false,"sfp_rxpower":"-40.00","sfp_serial":"D87B2338304","sfp_temperature":"51.562","sfp_txfault":false,"sfp_txpower":"-40.00","sfp_vendor":"FiberStore","sfp_voltage":"3.356","speed":1000,"stp_pathcost":20000,"stp_state":"forwarding","tx_broadcast":416500,"tx_bytes":397567018879,"tx_dropped":0,"tx_errors":0,"tx_multicast":2417485,"tx_packets":453438238,"up":true,"tx_bytes-r":116758,"rx_bytes-r":524926,"bytes-r":641685,"name":"cr-sw2.site1.foo.bar","masked":false,"aggregated_by":false},{"port_idx":10,"media":"SFP","port_poe":false,"poe_caps":0,"speed_caps":1048608,"op_mode":"switch","portconf_id":"597f622ef62e74498be19d83","autoneg":true,"dot1x_mode":"unknown","dot1x_status":"disabled","enable":false,"flowctrl_rx":false,"flowctrl_tx":false,"full_duplex":false,"is_uplink":false,"jumbo":false,"lldp_table":[],"rx_broadcast":0,"rx_bytes":0,"rx_dropped":0,"rx_errors":0,"rx_multicast":0,"rx_packets":0,"satisfaction":100,"sfp_found":false,"speed":0,"stp_pathcost":0,"stp_state":"disabled","tx_broadcast":0,"tx_bytes":0,"tx_dropped":0,"tx_errors":0,"tx_multicast":0,"tx_packets":0,"up":false,"tx_bytes-r":0,"rx_bytes-r":0,"bytes-r":0,"isolation":false,"name":"SFP 2","poe_mode":"off","stormctrl_bcast_enabled":false,"stormctrl_mcast_enabled":false,"stormctrl_ucast_enabled":false,"masked":false,"aggregated_by":false}],"cfgversion":"e6b97905f1f641e6","model":"US8P150","fw_caps":4906533,"mac":"f0:9f:c2:68:1c:53","led_override":"default","ethernet_table":[{"mac":"f0:9f:c2:68:1c:53","num_port":10,"name":"eth0"},{"mac":"f0:9f:c2:68:1c:54","name":"srv0"}],"port_overrides":[{"autoneg":true,"isolation":false,"name":"ge-0.wap1.site1.foo.bar","op_mode":"switch","poe_mode":"auto","port_idx":1,"portconf_id":"597f622ef62e74498be19d82","stormctrl_bcast_enabled":false,"stormctrl_mcast_enabled":false,"stormctrl_ucast_enabled":false},{"autoneg":true,"isolation":false,"name":"ge-0.wap2.site1.foo.bar","op_mode":"switch","poe_mode":"auto","port_idx":2,"portconf_id":"597f622ef62e74498be19d82","stormctrl_bcast_enabled
Sep 13 10:40:10 localhost unifi-poller[4130]: ":false,"stormctrl_mcast_enabled":false,"stormctrl_ucast_enabled":false},{"name":"unifi-video-cottage","poe_mode":"auto","port_idx":3,"portconf_id":"597f622ef62e74498be19d84"},{"autoneg":true,"isolation":false,"name":"Port 4","op_mode":"switch","poe_mode":"auto","port_idx":4,"portconf_id":"597f622ef62e74498be19d83","stormctrl_bcast_enabled":false,"stormctrl_mcast_enabled":false,"stormctrl_ucast_enabled":false},{"name":"Port 5","poe_mode":"auto","port_idx":5,"portconf_id":"597f622ef62e74498be19d82"},{"name":"en-0.ups1.site1.foo.bar","poe_mode":"off","port_idx":6,"portconf_id":"597f622ef62e74498be19d82"},{"name":"en-0.raspberrypi.site1.foo.bar","poe_mode":"off","port_idx":7,"portconf_id":"597f622ef62e74498be19d82"},{"poe_mode":"off","port_idx":8,"portconf_id":"597f622ef62e74498be19d83"},{"name":"cr-sw2.site1.foo.bar","port_idx":9,"portconf_id":"597f622ef62e74498be19d82"},{"autoneg":true,"isolation":false,"name":"SFP 2","op_mode":"switch","poe_mode":"off","port_idx":10,"portconf_id":"597f622ef62e74498be19d83","stormctrl_bcast_enabled":false,"stormctrl_mcast_enabled":false,"stormctrl_ucast_enabled":false}],"type":"usw","version":"4.0.54.10625","board_rev":12,"adopted":true,"name":"cr-sw1","stp_version":"rstp","config_network":{"type":"dhcp","ip":"192.168.1.214"},"jumboframe_enabled":false,"site_id":"597f622ef62e74498be19d79","dot1x_portctrl_enabled":false,"ip":"10.10.0.28","has_fan":false,"license_state":"registered","stp_priority":8192,"flowctrl_enabled":false,"inform_ip":"134.209.247.121","serial":"F09FC2681C53","has_temperature":true,"hw_caps":0,"mgmt_network_id":"597f622ef62e74498be19d7e","snmp_location":"cottage","switch_caps":{"feature_caps":1022,"max_mirror_sessions":1,"max_aggregate_sessions":5},"required_version":"3.3.11","unsupported":false,"unsupported_reason":0,"sys_error_caps":0,"two_phase_adopt":false,"device_id":"598c2e16f62eb3ad7244b62b","state":1,"last_seen":1568371207,"satisfaction":100,"known_cfgversion":"e6b97905f1f641e6","uptime":2893946,"_uptime":2893946,"locating":false,"connect_req
Sep 13 10:40:10 localhost unifi-poller[4130]: uest_ip":"84.240.91.119","connect_request_port":"56139","sys_stats":{"loadavg_1":"2.28","loadavg_15":"1.68","loadavg_5":"1.87","mem_buffer":0,"mem_total":262397952,"mem_used":131788800},"system-stats":{"cpu":"56.1","mem":"50.2","uptime":"2891844"},"ssh_session_table":[],"general_temperature":59,"overheating":false,"total_max_power":140,"downlink_table":[{"port_idx":1,"speed":1000,"full_duplex":true,"mac":"f0:9f:c2:79:8b:0a"},{"port_idx":2,"speed":1000,"full_duplex":true,"mac":"78:8a:20:20:5f:9d"}],"uplink":{"full_duplex":true,"ip":"10.10.0.28","mac":"f0:9f:c2:68:1c:53","name":"eth0","netmask":"255.255.255.0","num_port":10,"rx_bytes":931434428704,"rx_dropped":0,"rx_errors":0,"rx_multicast":0,"rx_packets":804298097,"speed":1000,"tx_bytes":397567018879,"tx_dropped":0,"tx_errors":0,"tx_packets":453438238,"up":true,"port_idx":9,"media":"SFP","max_speed":1000,"uplink_mac":"78:8a:20:fd:62:ee","uplink_remote_port":26,"type":"wire","tx_bytes-r":116758,"rx_bytes-r":524926},"uplink_depth":2,"dhcp_server_table":[],"upgradable":false,"adoptable_when_upgraded":false,"rollupgrade":false,"last_uplink":{"uplink_mac":"78:8a:20:fd:62:ee"},"next_interval":80,"next_heartbeat_at":1568371297,"considered_lost_at":1568371477,"stat":{"sw":{"site_id":"597f622ef62e74498be19d79","o":"sw","oid":"f0:9f:c2:68:1c:53","sw":"f0:9f:c2:68:1c:53","time":1567676100000,"datetime":"2019-09-05T09:35:00Z","rx_packets":3.28377767E8,"rx_bytes":3.47723382756E11,"rx_errors":0.0,"rx_dropped":0.0,"rx_crypts":0.0,"rx_frags":0.0,"tx_packets":3.33752292E8,"tx_bytes":3.48707873436E11,"tx_errors":0.0,"tx_dropped":0.0,"tx_retries":0.0,"rx_multicast":918801.0,"rx_broadcast":126620.0,"tx_multicast":5535779.0,"tx_broadcast":872315.0,"bytes":6.96431256192E11,"duration":6.94947E8,"port_1-rx_packets":4.2225772E7,"port_1-rx_bytes":4.791957175E9,"port_1-tx_packets":1.65409036E8,"port_1-tx_bytes":2.3815386298E11,"port_1-rx_multicast":390387.0,"port_1-tx_multicast":528424.0,"port_1-tx_broadcast":133081.0,"port_2-rx_packets":1720237.0,"port_2-rx_bytes":3.01605592E8,"port_2-tx_p
Sep 13 10:40:10 localhost unifi-poller[4130]: ackets":3334724.0,"port_2-tx_bytes":2.857029313E9,"port_2-rx_multicast":18983.0,"port_2-rx_broadcast":48208.0,"port_2-tx_multicast":899828.0,"port_2-tx_broadcast":94471.0,"port_3-rx_packets":7.1541662E7,"port_3-rx_bytes":9.8190437738E10,"port_3-tx_packets":4.0955965E7,"port_3-tx_bytes":3.045086966E9,"port_3-tx_multicast":918811.0,"port_3-tx_broadcast":142660.0,"port_5-tx_packets":1032805.0,"port_5-tx_bytes":1.64499058E8,"port_5-tx_multicast":825463.0,"port_5-tx_broadcast":142678.0,"port_6-rx_packets":820084.0,"port_6-rx_bytes":9.4615774E7,"port_6-tx_packets":1816504.0,"port_6-tx_bytes":2.43823307E8,"port_6-tx_multicast":913019.0,"port_6-tx_broadcast":115698.0,"port_7-rx_packets":2740205.0,"port_7-rx_bytes":4.55707009E8,"port_7-tx_packets":3409285.0,"port_7-tx_bytes":4.69288209E8,"port_7-rx_multicast":31714.0,"port_7-tx_multicast":887097.0,"port_7-tx_broadcast":142647.0,"port_9-rx_packets":2.09150305E8,"port_9-rx_bytes":2.43840711657E11,"port_9-tx_packets":1.17793973E8,"port_9-tx_bytes":1.03774283603E11,"port_9-rx_multicast":378578.0,"port_9-rx_broadcast":41690.0,"port_9-tx_multicast":563137.0,"port_9-tx_broadcast":101080.0,"port_1-rx_broadcast":9689.0,"port_5-rx_packets":179502.0,"port_5-rx_bytes":4.8347811E7,"port_5-rx_multicast":93348.0,"port_6-rx_broadcast":26981.0,"port_6-rx_multicast":5791.0,"port_3-rx_broadcast":19.0,"port_7-rx_broadcast":32.0,"port_5-rx_broadcast":1.0}},"tx_bytes":931434428704,"rx_bytes":397567018879,"bytes":1329001447583,"num_sta":4,"user-num_sta":4,"guest-num_sta":0} (marshal err: <nil>)
Sep 13 10:40:10 localhost unifi-poller[4130]: 2019/09/13 10:40:10.461762 devices.go:80: [DEBUG] The above payload can prove useful during torubleshooting when you open an Issue:
Sep 13 10:40:10 localhost unifi-poller[4130]: 2019/09/13 10:40:10.461785 devices.go:81: [DEBUG] ==- https://github.com/golift/unifi/issues/new -==`

**Comment by jussisallinen** [comment]
This is also open in davidnewhall/unifi-poller:
[https://github.com/davidnewhall/unifi-poller/issues/117](url)

**Comment by davidnewhall** [comment]
We'll triage there.
