### ISSUE TITLE
2 usw's

### ISSUE THREAD

**Issue by keesnobel** [golift/unifi#9]
unidev.go:155: [ERROR] json.Unmarshal(usw): json: cannot unmarshal number into Go struct field .aggregated_by of type bool

gave me this err 

only 1 usw is logged

**Comment by davidnewhall** [comment]
I think https://github.com/golift/unifi/pull/7 fixes this. Can you test against master?

**Comment by davidnewhall** [comment]
You'll also need to use this branch https://github.com/davidnewhall/unifi-poller/pull/18

**Comment by davidnewhall** [comment]
I'll get all this sorted shortly. I've been very busy lately and haven't been able to get around to finishing up the new features I started.

**Comment by jsloyer** [comment]
I tried with the latest from master and getting the following:

```
9/05/30 17:15:47.770854 types.go:36: [DEBUG] Unmarshalling Device Type: usw
2019/05/30 17:15:47.772334 types.go:36: [DEBUG] Unmarshalling Device Type: usw
2019/05/30 17:15:47.774843 types.go:36: [DEBUG] Unmarshalling Device Type: uap
2019/05/30 17:15:47.778110 types.go:36: [DEBUG] Unmarshalling Device Type: uap
2019/05/30 17:15:47.781390 types.go:36: [DEBUG] Unmarshalling Device Type: usw
2019/05/30 17:15:47.787158 types.go:36: [DEBUG] Unmarshalling Device Type: usw
2019/05/30 17:15:47.790417 types.go:36: [DEBUG] Unmarshalling Device Type: uap
2019/05/30 17:15:47.791890 types.go:36: [DEBUG] Unmarshalling Device Type: ugw
2019/05/30 17:15:47.792378 types.go:43: [ERROR] json.Unmarshal(ugw): json: cannot unmarshal string into Go struct field .rx_bytes of type float64
```

And also the following:
```
2019/05/30 17:15:47.793446 types.go:36: [DEBUG] Unmarshalling Device Type: uap
2019/05/30 17:15:47.795220 types.go:36: [DEBUG] Unmarshalling Device Type: usw
2019/05/30 17:15:47.805118 main.go:182: [ERROR] infdb.Write(bp): {"error":"field type conflict: input field \"roll_upgrade\" on measurement \"uap\" is type string, already exists as type boolean"}
```

**Comment by davidnewhall** [comment]
I'm confused. In master, `roll_upgrade` in UAP is a bool. It was a string yesterday, but I made a commit last night to fix that. https://github.com/golift/unifi/commit/034a62e1cb6ef13e724cfab9b8f87dbb130d493c#diff-b766138bdcf88a44807d18d09f084bafR70 - master (or 2.0.0) should not produce that error.

This error `json: cannot unmarshal string into Go struct field .rx_bytes of type float64` is another case of the controller wrapping floats in quotes - I'll have to fix that in another contribution.

**Comment by jsloyer** [comment]
Getting farther, it looks like to be the same error on tx_bytes as well

```
2019/05/30 19:07:40.552472 types.go:36: [DEBUG] Unmarshalling Device Type: usw
2019/05/30 19:07:40.553943 types.go:36: [DEBUG] Unmarshalling Device Type: usw
2019/05/30 19:07:40.556500 types.go:36: [DEBUG] Unmarshalling Device Type: uap
2019/05/30 19:07:40.559479 types.go:36: [DEBUG] Unmarshalling Device Type: uap
2019/05/30 19:07:40.562366 types.go:36: [DEBUG] Unmarshalling Device Type: usw
2019/05/30 19:07:40.567671 types.go:36: [DEBUG] Unmarshalling Device Type: usw
2019/05/30 19:07:40.571896 types.go:36: [DEBUG] Unmarshalling Device Type: uap
2019/05/30 19:07:40.573490 types.go:36: [DEBUG] Unmarshalling Device Type: ugw
2019/05/30 19:07:40.574064 types.go:43: [ERROR] json.Unmarshal(ugw): json: cannot unmarshal string into Go struct field .tx_bytes of type float64
```

**Comment by davidnewhall** [comment]
Just popped a commit in to wrap txbytes. https://github.com/golift/unifi/commit/bffc6469cecb445206d7d912d1818fb471d347be

Give it a go now, please.

**Comment by davidnewhall** [comment]
Let me know if you're still having problems please! Thanks!
